[package]
name = "nstream-rayon"
version = "0.1.0"
authors = ["Jeff Hammond <jeff.r.hammond@intel.com>", "Thomas Hayward-Schneider <thomas.hayward@ipp.mpg.de>", "Sajid Ali <sasyed@fnal.gov>"]

edition = "2021"

[dependencies]
rayon = "1.5"
