# Mirrors common/make.defs.oneapi's CC/CXX/FC selection.
#
#   CC=icx -std=c11 -pthread
#   FC=ifx -std18 -fpp
#   CXX=icpx -std=c++20 -pthread
#
# Unlike gcc.cmake/llvm.cmake/nvhpc.cmake, oneAPI needs more than PATH: MKL
# detection (find_package(BLAS)) needs MKLROOT set, which normally comes
# from sourcing setvars.sh -- set it directly here instead so this
# toolchain file is self-sufficient without requiring that first. This
# matches make.defs.oneapi's own CBLASFLAG=-DMKL -qmkl (MKL is the intended
# BLAS backend for this toolchain, not OpenBLAS).

set(CMAKE_C_COMPILER       /opt/intel/oneapi/compiler/2026.0/bin/icx   CACHE STRING "")
set(CMAKE_CXX_COMPILER     /opt/intel/oneapi/compiler/2026.0/bin/icpx  CACHE STRING "")
set(CMAKE_Fortran_COMPILER /opt/intel/oneapi/compiler/2026.0/bin/ifx   CACHE STRING "")

set(ENV{MKLROOT} /opt/intel/oneapi/mkl/2026.0)
set(ENV{TBBROOT} /opt/intel/oneapi/tbb/2023.0)

# icx/icpx/ifx-built binaries link against Intel's own runtime libraries
# (libimf.so etc., not just libc/libstdc++) -- without this on
# LD_LIBRARY_PATH, any built binary (including CMake's own try_compile/
# try_run probes) fails at *run* time with "error while loading shared
# libraries: libimf.so: cannot open shared object file", even though it
# compiled and linked fine. Normally comes from sourcing setvars.sh.
if(DEFINED ENV{LD_LIBRARY_PATH})
  set(ENV{LD_LIBRARY_PATH} "/opt/intel/oneapi/compiler/2026.0/lib:/opt/intel/oneapi/tbb/2023.0/lib/intel64/gcc4.8:$ENV{LD_LIBRARY_PATH}")
else()
  set(ENV{LD_LIBRARY_PATH} "/opt/intel/oneapi/compiler/2026.0/lib:/opt/intel/oneapi/tbb/2023.0/lib/intel64/gcc4.8")
endif()

# make.defs.oneapi's MPI targets are built with Intel's own MPI wrappers
# (mpiicx/mpiifx, via I_MPI_ROOT normally set by setvars.sh), which produce
# MPI_F08 .mod files that only ifx itself can read. Without this on PATH,
# find_package(MPI) instead picks up whatever generic mpif90 is on the
# system (this machine's system OpenMPI), which was built by gfortran --
# its .mod files aren't binary-compatible with ifx ("This module file was
# not generated by any release of this compiler"), breaking every
# MPI-Fortran target. The mpiicx/mpiifx wrapper scripts also need
# I_MPI_ROOT set (normally by setvars.sh) -- without it they substitute a
# literal broken placeholder path ("I_MPI_SUBSTITUTE_INSTALLDIR") into
# their own -I/-L flags instead of the real install location.
set(ENV{I_MPI_ROOT} /opt/intel/oneapi/mpi/2021.18)
set(ENV{PATH} "/opt/intel/oneapi/mpi/2021.18/bin:$ENV{PATH}")
# LIBRARY_PATH (compile/link-time -l search, distinct from LD_LIBRARY_PATH's
# runtime search) is needed by third-party autobuilt dependencies (e.g.
# FORTRAN's Global Arrays/ARMCI-MPI) whose own ./configure invokes the
# plain C compiler directly with -lmpifort rather than through an MPI
# wrapper script -- without it, linking fails outright ("cannot find
# -lmpifort").
if(DEFINED ENV{LIBRARY_PATH})
  set(ENV{LIBRARY_PATH} "/opt/intel/oneapi/mpi/2021.18/lib:$ENV{LIBRARY_PATH}")
else()
  set(ENV{LIBRARY_PATH} "/opt/intel/oneapi/mpi/2021.18/lib")
endif()
