#[=======================================================================[.rst:
PRKCFeatures
-------------

try_compile()-based probes for C compiler capabilities that aren't
libraries CMake can find_package()/find_library() for -- they're compiler
flags that either work or don't. Mirrors the OFFLOADFLAG/OPENACCFLAG/
CILKFLAG logic spread across common/make.defs.*, for the C language (see
PRKFortranFeatures.cmake for the Fortran equivalents).
#]=======================================================================]

include(CheckCSourceCompiles)

function(prk_check_openmp_offload_c)
  if(DEFINED PRK_C_OPENMP_OFFLOAD_FLAG)
    return()
  endif()
  set(_src "int main(void) { int s = 0;\n#pragma omp target map(tofrom: s)\n  { s = 1; }\n  return s; }\n")
  if(NOT OpenMP_C_FOUND)
    set(PRK_C_OPENMP_OFFLOAD_FLAG "" CACHE STRING "Compiler flags enabling C OpenMP target offload")
    message(STATUS "C OpenMP target offload: not probed, no OpenMP found")
    return()
  endif()
  if(CMAKE_C_COMPILER_ID MATCHES "GNU")
    set(_candidate "-fopenmp;-foffload=-O3")
  elseif(CMAKE_C_COMPILER_ID MATCHES "Clang")
    set(_candidate "-fopenmp;-fopenmp-targets=x86_64-pc-linux-gnu")
  else()
    set(_candidate "")
  endif()
  if(_candidate STREQUAL "")
    set(PRK_C_OPENMP_OFFLOAD_FLAG "" CACHE STRING "Compiler flags enabling C OpenMP target offload")
    message(STATUS "C OpenMP target offload: not probed, no known flag for ${CMAKE_C_COMPILER_ID}")
    return()
  endif()
  set(CMAKE_REQUIRED_FLAGS "${_candidate}")
  check_c_source_compiles("${_src}" PRK_C_OPENMP_OFFLOAD_COMPILES)
  unset(CMAKE_REQUIRED_FLAGS)
  if(PRK_C_OPENMP_OFFLOAD_COMPILES)
    set(PRK_C_OPENMP_OFFLOAD_FLAG "${_candidate}" CACHE STRING "Compiler flags enabling C OpenMP target offload")
    message(STATUS "C OpenMP target offload (${_candidate}): compiles and links")
  else()
    set(PRK_C_OPENMP_OFFLOAD_FLAG "" CACHE STRING "Compiler flags enabling C OpenMP target offload")
    message(STATUS "C OpenMP target offload: compiler rejected ${_candidate}")
  endif()
endfunction()

function(prk_check_openacc_links_c)
  if(DEFINED PRK_C_OPENACC_WORKS)
    return()
  endif()
  if(NOT OpenACC_C_FOUND)
    set(PRK_C_OPENACC_WORKS FALSE CACHE BOOL "OpenACC C actually links/codegens, not just compiles")
    return()
  endif()
  # find_package(OpenACC) only checks the compiler accepts the flag, not
  # that the accelerator codegen/link actually succeeds (see the Fortran
  # equivalent probe in PRKFortranFeatures.cmake for why this matters).
  set(_src "int main(void) { int s[10]; int i;\n#pragma acc parallel loop\n  for (i=0;i<10;i++) s[i]=i;\n  return s[0]; }\n")
  set(CMAKE_REQUIRED_FLAGS "${OpenACC_C_FLAGS}")
  check_c_source_compiles("${_src}" PRK_C_OPENACC_LINK_COMPILES)
  unset(CMAKE_REQUIRED_FLAGS)
  if(PRK_C_OPENACC_LINK_COMPILES)
    set(PRK_C_OPENACC_WORKS TRUE CACHE BOOL "OpenACC C actually links/codegens, not just compiles")
    message(STATUS "C OpenACC (${OpenACC_C_FLAGS}): compiles and links")
  else()
    set(PRK_C_OPENACC_WORKS FALSE CACHE BOOL "OpenACC C actually links/codegens, not just compiles")
    message(STATUS "C OpenACC: found but accelerator codegen/link failed (broken offload toolchain?), skipping")
  endif()
endfunction()

function(prk_check_cilk_c)
  if(DEFINED PRK_C_CILK_FLAG)
    return()
  endif()
  set(_src "#include <cilk/cilk.h>\nint main(void) { cilk_spawn (void)0; cilk_sync; return 0; }\n")
  set(CMAKE_REQUIRED_FLAGS "-fcilkplus")
  check_c_source_compiles("${_src}" PRK_C_CILK_COMPILES)
  unset(CMAKE_REQUIRED_FLAGS)
  if(PRK_C_CILK_COMPILES)
    set(PRK_C_CILK_FLAG "-fcilkplus" CACHE STRING "Compiler flag enabling Cilk Plus")
    message(STATUS "C Cilk Plus (-fcilkplus): supported")
  else()
    set(PRK_C_CILK_FLAG "" CACHE STRING "Compiler flag enabling Cilk Plus")
    message(STATUS "C Cilk Plus: not supported by ${CMAKE_C_COMPILER_ID} (dropped from modern gcc/clang)")
  endif()
endfunction()

function(prk_check_avx_c)
  if(DEFINED PRK_C_AVX_FLAG)
    return()
  endif()
  set(_src "#include <immintrin.h>\nint main(void) { __m256d a = _mm256_set1_pd(1.0); __m256d b = _mm256_add_pd(a,a); return (int)_mm256_cvtsd_f64(b); }\n")
  set(CMAKE_REQUIRED_FLAGS "-mavx2")
  check_c_source_compiles("${_src}" PRK_C_AVX_COMPILES)
  unset(CMAKE_REQUIRED_FLAGS)
  if(PRK_C_AVX_COMPILES)
    set(PRK_C_AVX_FLAG "-mavx2" CACHE STRING "Compiler flag enabling AVX2 intrinsics")
    message(STATUS "C AVX2 (-mavx2): supported")
  else()
    set(PRK_C_AVX_FLAG "" CACHE STRING "Compiler flag enabling AVX2 intrinsics")
    message(STATUS "C AVX2: not supported (compile-only probe; target CPU may still lack it at runtime)")
  endif()
endfunction()
