name: Makefile CI

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Test C++
      run: CXX=g++ bash ./travis/build-run-prk.sh /tmp allcxx
      
    - name: Test Fortran
      run: FC=gfortran bash ./travis/build-run-prk.sh /tmp allfortran
      
    - name: Test C11
      run: CC=gcc bash ./travis/build-run-prk.sh /tmp allc1z
      
    - name: Test Python
      run: bash ./travis/build-run-prk.sh /tmp allpython
