name: Makefile CI

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup
      run: cp common/make.defs.gcc common/make.defs
      
    - name: Build
      run: make -C allcxx
      
    - name: Run C++
      run: ./travis/build-run-prk.sh /tmp allcxx
